server:
  port: 18081

spring:
  application:
    name: demo-json-service
  cloud:
    nacos:
      server-addr: 82.156.139.106:8848
      username: nacos
      password: nacos
      discovery:
        enabled: true
        namespace: modelGateway

management:
  endpoints:
    web:
      exposure:
        include: health,info
